server:
  tomcat:
    uri-encoding: UTF-8
  port: 8000

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  devtools:
    restart:
      poll-interval: 4s

  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/pro_spring?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: spring
    password: qZF08fDcidSRJ2CI
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      filters: slf4j

  redis:
    database: 0
    host: localhost
    port: 6379
    password: KSNwJwcOUj2KBLJQ
    lettuce:
      pool:
        max-active: 4

  data:
    mongodb:
      database: log
      host: localhost
      port: 27017

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

  main:
    lazy-initialization: false

  application:
    name: user-server

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codve.user.model.data.object
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  expire: 300s
  secret: 123456

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      profile: "用户服务中心"
