server:
  port: 8100

spring:
  application:
    name: article-server

  datasource:
    url: jdbc:mysql://localhost:3306/pro_spring?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: spring
    password: qZF08fDcidSRJ2CI
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      filters: slf4j

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      profile: "CMS 服务"

user-server:
  ribbon:
    listOfServers: http://localhost:8000, http://localhost:8002
    MaxAutoRetriesNextServer: 0
    MaxAutoRetries: 0
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList