server:
  port: 8300

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"