server:
  port: 8300

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  retryable: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  

